### ISSUE TITLE
[Integration] More Villagers

### ISSUE THREAD

**Issue by ConqAra** [dvitski/onastick#1]
compatibility for morevillagers mod would be nice, if you have the mod installed it would add more sticks of workstations from morevillagers mod

mod: [https://www.curseforge.com/minecraft/mc-mods/more-villagers-fabric]( https://www.curseforge.com/minecraft/mc-mods/more-villagers-fabric)

**Comment by dvitski** [comment]
None of these work stations have functionality, as far as I can tell? We don't add a Fletching Table on a Stick, for example, (yet..) so I'm not sure what we could add integration for
